### ISSUE TITLE
Different namespaces in operator.yaml

### ISSUE THREAD

**Issue by headconnect** [rook/cassandra#27]
https://github.com/rook/cassandra/blob/acc9f9697631729988057232daddcf177d61cef6/cluster/examples/kubernetes/cassandra/operator.yaml#L95

Should it not be using the `rook-cassandra-system` namespace like the resources declared above?

**Comment by travisn** [comment]
Yes, looks like this was an unintentional change in v1.7.3 with #23.

**Comment by headconnect** [comment]
Many thanks :)
