### ISSUE TITLE
Cassandra - mbind: Operation not permitted

### ISSUE THREAD

**Issue by AceHack** [rook/cassandra#4]
The logs are flooded with this message, please fix.

I created an issue on the Cassandra docker container as well
https://github.com/docker-library/cassandra/issues/203

**Comment by AceHack** [comment]
Bump

**Comment by frbor** [comment]
This might be relevant: [https://stackoverflow.com/questions/55559386/how-to-fix-mbind-operation-not-permitted-in-mysql-error-log](https://stackoverflow.com/questions/55559386/how-to-fix-mbind-operation-not-permitted-in-mysql-error-log] for docker/docker-compose.

**Comment by travisn** [comment]
See #29.
